version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Teste@Teste123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - compose-bridge
    volumes:
      - sqlserverdb:/var/opt/mssql
  
  apiprodutos:
    build: 
      context: .
      dockerfile: Dockerfile
    image: apiprodutos:1.0
    networks:
      - compose-bridge
    ports: 
      - "8680:8080"
    depends_on:
      - sqlserver

  apiestoque:
    build: 
      context: ..\ApiEstoque
      dockerfile: Dockerfile
    image: apiestoque:1.0
    container_name: apiestoque
    networks:
      - compose-bridge
    ports:
      - "8681:8080"
    depends_on:
      - sqlserver
  
    Rabbit: 
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - 5672:5672
        - 25672:25672
        - 15672:15672
      volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
      environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=#user#
    restart: always
  
networks:
  compose-bridge:
    driver: bridge

volumes:
  sqlserverdb:
